log-level: silent
allow-lan: true
redir-port: 1080
tproxy-port: 1081
ipv6: false
mode: rule
geodata-mode: true
geodata-loader: memconservative
geo-auto-update: true
geo-update-interval: 24
keep-alive-interval: 15
keep-alive-idle: 15
disable-keep-alive: false
external-controller: 0.0.0.0:9090
external-ui: zashboard
external-ui-url: https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip
profile:
  store-selected: true

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]

proxy-groups:
  - name: Свободный интернет
    type: url-test
    url: http://www.msftncsi.com/ncsi.txt
    interval: 120
    tolerance: 50
    lazy: false
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Available_1.png
    include-all: true
    

  - name: YouTube
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png
    use:
      - subscription
    proxies:
      - Свободный интернет
      - DIRECT

  - name: Discord
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Discord.png
    use:
      - subscription
    
    proxies:
      - Свободный интернет
      - DIRECT

  - name: Twitch
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Twitch.png
    use:
      - subscription
    
    proxies:
      - Свободный интернет
      - DIRECT

  - name: Кинотеатры
    type: select
    icon: https://github.com/amatol/xkeen-configuration/raw/refs/heads/main/group-icons/kino.png
    use:
      - subscription
    
    proxies:
      - Свободный интернет
      - DIRECT

  - name: Meta
    type: select
    icon: https://github.com/zxc-rv/assets/raw/refs/heads/main/group-icons/meta.png
    use:
      - subscription
    
    proxies:
      - Свободный интернет
      - DIRECT

  - name: Microsoft
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Microsoft.png
    use:
      - subscription
    
    proxies:
      - Свободный интернет
      - DIRECT

  - name: Spotify
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Spotify.png
    use:
      - subscription
    
    proxies:
      - Свободный интернет
      - DIRECT

  - name: Telegram
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png
    use:
      - subscription
    
    proxies:
      - Свободный интернет
      - DIRECT

  - name: Community
    type: select
    icon: https://github.com/amatol/xkeen-configuration/raw/refs/heads/main/group-icons/community.png
    use:
      - subscription
    
    proxies:
      - Свободный интернет
      - DIRECT

  - name: Cloudflare
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Cloudflare.png
    use:
      - subscription
    
    proxies:
      - PASS
      - Свободный интернет
      - DIRECT

  - name: AI
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Bot.png
    use:
      - subscription
    
    proxies:
      - Свободный интернет
      - DIRECT

  - name: Twitter
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Twitter.png
    use:
      - subscription
    
    proxies:
      - Свободный интернет
      - DIRECT

  - name: TikTok
    type: select
    icon: https://github.com/amatol/xkeen-configuration/raw/refs/heads/main/group-icons/tiktok.png
    use:
      - subscription
    
    proxies:
      - Свободный интернет
      - DIRECT

  - name: PlayStation
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/PlayStation.png
    use:
      - subscription
    
    proxies:
      - Свободный интернет
      - DIRECT

  - name: Nintendo
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Nintendo.png
    use:
      - subscription
    
    proxies:
      - Свободный интернет
      - DIRECT

  - name: LG
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Apple_TV.png
    use:
      - subscription
    proxies:
      - Свободный интернет
      - DIRECT

  - name: TCL
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Apple_TV.png
    use:
      - subscription
    proxies:
      - Свободный интернет
      - DIRECT

  - name: Steam
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Steam.png
    use:
      - subscription
    
    proxies:
      - Свободный интернет
      - DIRECT

  - name: Steam (чат и голос)
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Steam.png
    use:
      - subscription
    
    proxies:
      - Свободный интернет
      - DIRECT

  - name: Epic Games
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Epic_Games.png
    use:
      - subscription
    
    proxies:
      - Свободный интернет
      - DIRECT

  - name: EA
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Game.png
    use:
      - subscription
    
    proxies:
      - Свободный интернет
      - DIRECT

  - name: Ubisoft
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Game.png
    use:
      - subscription
    
    proxies:
      - Свободный интернет
      - DIRECT

  - name: Mihoyo
    type: select
    icon: https://raw.githubusercontent.com/clash-verge-rev/icon-hub/main/mihoyo/ys.png
    use:
      - subscription
    
    proxies:
      - Свободный интернет
      - DIRECT

  - name: Игры (прокси)
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Game.png
    use:
      - subscription
    
    proxies:
      - Свободный интернет
      - DIRECT

  - name: OTHERS
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png
    use:
      - subscription
    
    proxies:
      - Свободный интернет
      - DIRECT

  - name: QUIC
    type: select
    icon: https://github.com/zxc-rv/assets/raw/refs/heads/main/group-icons/quic.png
    proxies:
      - REJECT
      - PASS

# Подключение с использованием подписки
proxy-providers:
  subscription:
    type: http
    url:  ${SUB_A}# <------------ ЗДЕСЬ ВСТАВИТЬ ССЫЛКУ НА ВАШУ ПОДПИСКУ
    path: ./proxy-providers/subscription.yaml
    interval: 3600
    health-check:
      enable: true
      url: http://www.msftncsi.com/ncsi.txt
      interval: 120

rule-providers:
  refilter-domains:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/re-filter/domain-rule.mrs
    path: ./rule-providers/refilter-domains.mrs
    interval: 86400

  refilter-ips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/re-filter/ip-rule.mrs
    path: ./rule-providers/refilter-ips.mrs
    interval: 86400

  kino:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/amatol/xkeen-configuration/raw/refs/heads/main/rules/kino.mrs
    path: ./rule-providers/kino-domains.mrs
    interval: 86400

  patreon:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/patreon.mrs
    path: ./rule-providers/patreon-domains.mrs
    interval: 86400

  tiktok:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/tiktok.mrs
    path: ./rule-providers/tiktok-domains.mrs
    interval: 86400

  microsoft:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/microsoft.mrs
    path: ./rule-providers/microsoft-domains.mrs
    interval: 86400

  playstation:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/playstation.mrs
    path: ./rule-providers/playstation-domains.mrs
    interval: 86400

  nintendo:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/nintendo.mrs
    path: ./rule-providers/nintendo-domains.mrs
    interval: 86400

  lg:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/Ivan-Stepalin/xkeen-config-mihomo/main/rules/lg.yaml
    path: ./rule-providers/lg.yaml
    interval: 86400

  tcl:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/Ivan-Stepalin/xkeen-config-mihomo/main/rules/tcl.yaml
    path: ./rule-providers/tcl.yaml
    interval: 86400

  steam:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/steam.mrs
    path: ./rule-providers/steam-domains.mrs
    interval: 86400

  epicgames:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/epicgames.mrs
    path: ./rule-providers/epicgames-domains.mrs
    interval: 86400

  ea:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/ea.mrs
    path: ./rule-providers/ea-domains.mrs
    interval: 86400

  ubisoft:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/ubisoft.mrs
    path: ./rule-providers/ubisoft-domains.mrs
    interval: 86400

  steam-chat:
    type: inline
    behavior: classical
    format: text
    payload:
      - DOMAIN-SUFFIX,steamcommunity.com
      - DOMAIN-SUFFIX,steam-chat.com

  mihoyo:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/Ivan-Stepalin/xkeen-config-mihomo/main/rules/mihoyo.yaml
    path: ./rule-providers/mihoyo.yaml
    interval: 86400

  community:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/Ivan-Stepalin/xkeen-config-mihomo/main/rules/community.mrs
    path: ./rule-providers/community-domains.mrs
    interval: 86400

  cloudflare-ips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/cloudflare.mrs
    path: ./rule-providers/cloudflare-ips.mrs
    interval: 86400

  discord:
    type: inline
    behavior: classical
    format: text
    payload:
      - AND,((DOMAIN-KEYWORD,discord),(NOT,((DOMAIN-SUFFIX,ru))))
      - AND,((RULE-SET,cloudflare-ips,no-resolve),(NETWORK,TCP),(OR,((DST-PORT,2000-2300),(DST-PORT,8443))))
      - AND,((RULE-SET,cloudflare-ips,no-resolve),(NETWORK,UDP),(OR,((DST-PORT,19200-19400),(DST-PORT,50000-51000))))
      - AND,((IP-CIDR,5.200.14.128/25,no-resolve),(NETWORK,UDP),(DST-PORT,50000-51000))
      - AND,((IP-CIDR,34.0.0.0/15,no-resolve),(NETWORK,UDP),(DST-PORT,50000-51000))
      - AND,((IP-CIDR,34.2.0.0/15,no-resolve),(NETWORK,UDP),(DST-PORT,50000-51000))
      - AND,((IP-CIDR,35.192.0.0/11,no-resolve),(NETWORK,UDP),(DST-PORT,50000-51000))
      - AND,((IP-CIDR,66.22.192.0/18,no-resolve),(NETWORK,UDP),(DST-PORT,50000-51000))
      - AND,((IP-CIDR,138.128.136.0/21,no-resolve),(NETWORK,UDP),(DST-PORT,50000-51000))

  telegram-ips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/telegram.mrs
    path: ./rule-providers/telegram-ips.mrs
    interval: 86400

  meta-ips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/zxc-rv/assets/raw/refs/heads/main/rules/meta-ips.mrs
    path: ./rule-providers/meta-ips.mrs
    interval: 86400

  refilter-noech:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/re-filter/re-filter-noech.mrs
    path: ./rule-providers/refilter-noech.mrs
    interval: 86400

  refilter-ech:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/re-filter/re-filter-ech.mrs
    path: ./rule-providers/refilter-ech.mrs
    interval: 86400

  torrent-trackers:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/other/torrent-trackers.mrs
    path: ./rule-providers/torrent-trackers.mrs

  torrent-clients:
    type: http
    behavior: classical
    format: yaml
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/other/torrent-clients.yaml
    path: ./rule-providers/torrent-clients.yaml
    interval: 86400

  AI-custom:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/Ivan-Stepalin/xkeen-config-mihomo/main/rules/AI.yaml
    path: ./rule-providers/ai-custom.yaml
    interval: 86400

  others:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/Ivan-Stepalin/xkeen-config-mihomo/main/rules/others.yaml
    path: ./rule-providers/others.yaml
    interval: 86400

  games-proxy:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/Ivan-Stepalin/xkeen-config-mihomo/main/rules/games-proxy.yaml
    path: ./rule-providers/games-proxy.yaml
    interval: 86400

rules:
  - AND,((DST-PORT,443),(NETWORK,UDP)),QUIC
  - OR,((DOMAIN-SUFFIX,gql.twitch.tv),(DOMAIN-SUFFIX,usher.ttvnw.net)),Свободный интернет # Разблокировка высокого качества на Twitch.tv
  - GEOSITE,category-ai-!cn,AI
  - RULE-SET,AI-custom,AI
  - GEOSITE,spotify,Spotify
  - OR,((GEOSITE,youtube),(DOMAIN-SUFFIX,googleusercontent.com)),YouTube
  - GEOSITE,twitch,Twitch
  - GEOSITE,twitter,Twitter
  - RULE-SET,discord,Discord
  - OR,((GEOSITE,meta),(RULE-SET,meta-ips,no-resolve)),Meta
  - RULE-SET,microsoft,Microsoft
  - OR,((GEOSITE,telegram),(RULE-SET,telegram-ips,no-resolve)),Telegram
  - OR,((GEOSITE,cloudflare),(RULE-SET,cloudflare-ips)),Cloudflare
  - RULE-SET,kino,Кинотеатры
  - RULE-SET,community,Community
  - RULE-SET,tiktok,TikTok
  - RULE-SET,patreon,Свободный интернет
  - RULE-SET,playstation,PlayStation
  - RULE-SET,nintendo,Nintendo
  - RULE-SET,lg,LG
  - RULE-SET,tcl,TCL
  - RULE-SET,steam-chat,Steam (чат и голос)
  - RULE-SET,steam,Steam
  - RULE-SET,epicgames,Epic Games
  - RULE-SET,ea,EA
  - RULE-SET,ubisoft,Ubisoft
  - RULE-SET,mihoyo,Mihoyo
  - RULE-SET,games-proxy,Игры (прокси)
  - RULE-SET,others,OTHERS
  - RULE-SET,refilter-domains,Свободный интернет
  - RULE-SET,refilter-ips,Свободный интернет
  - RULE-SET,torrent-clients,DIRECT
  - RULE-SET,torrent-trackers,DIRECT
  - MATCH,DIRECT
